
#
# SPDX-License-Identifier: Apache-2.0
#

OrdererOrgs:
  - Name: orderer
    Domain: files.com
    Specs:
      - Hostname: orderer
        SANS:
            - "localhost"
            - "127.0.0.1"

PeerOrgs:
  - Name: bob
    Domain: bob.files.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

  - Name: alice
    Domain: alice.files.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - "localhost"
    Users:
      Count: 1

