
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.files.com:
  peer0.bob.files.com:
  peer0.alice.files.com:

services:
  peer-base:
    image: hyperledger/fabric-peer:$IMAGE_TAG
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_ADDRESSAUTODETECT=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start
    volumes:
    - /var/run/:/host/var/run/

  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=orderer
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ./crypto-config/ordererOrganizations/files.com/orderers/orderer.files.com/msp:/var/hyperledger/orderer/msp
    - orderer.files.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050


  bob:
    container_name: bob
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=bob.peer0
      - CORE_PEER_ADDRESS=bob:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=bob:7051
      - CORE_PEER_LOCALMSPID=bob
      - CORE_CHAINCODE_LOGGING_SHIM=INFO
    volumes:
        - ./crypto-config/peerOrganizations/bob.files.com/peers/peer0.bob.files.com/msp:/etc/hyperledger/fabric/msp
        - peer0.bob.files.com:/var/hyperledger/production
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
    ports:
      - 7051:7051
      - 7053:7053

  alice:
    container_name: alice
    extends:
      service: peer-base
    environment:
      - CORE_PEER_ID=alice.peer0
      - CORE_PEER_ADDRESS=alice:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=alice:7051
      - CORE_PEER_LOCALMSPID=alice
    volumes:
        - ./crypto-config/peerOrganizations/alice.files.com/peers/peer0.alice.files.com/msp:/etc/hyperledger/fabric/msp
        - peer0.alice.files.com:/var/hyperledger/production
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
    ports:
      - 8051:7051
      - 8053:7053

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=bob:7051
      - CORE_PEER_LOCALMSPID=bob
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/bob.files.com/users/Admin@bob.files.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
    depends_on:
      - orderer
      - bob
      - alice

  ca.bob:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-bob
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.bob.files.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/03cbfa56748157abc1f3488156dbcea0e67ee4df0219b66626abf277b30aaa15_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.bob.files.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/03cbfa56748157abc1f3488156dbcea0e67ee4df0219b66626abf277b30aaa15_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/bob.files.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.bob

  ca.alice:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-alice
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.alice.files.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/2204d87e4d534fed44db70f8465209bb7c9343c1cf65154b1ac6c0da9683250b_sk
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.alice.files.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/2204d87e4d534fed44db70f8465209bb7c9343c1cf65154b1ac6c0da9683250b_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/alice.files.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.alice
